name: moviera
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Állapotkezelés és hitelesítés
  provider: ^6.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1

  # Adatbázis és hálózat
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
